collections:
  documentation:
    title: Documentation
    render: true
    output: true
  api:
    title: APIs
    render: true
    output: true
main_links:
#  -
#    title: 
#    link: /index.html
#  -
#    title: 2nd layout
#    link: /index2.html
#  -
#    title: 3rd layout
#    link: /index3.html
#  -
#    title: 4th layout
#    link: /index4.html
defaults:
  -
    scope:
      path: ""
    values:
      layout: multi
      sidebar: true
      body_class: docs fixed-width multi-page
